### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by MansM** [giantswarm/etcd-backup-operator#174]
As a non-aws user
I would like to be able to configure an endpoint for S3
in order to be able to use the etcd-backup-operator on prem

At work we have an S3 back end that compatible with AWS-S3 (example: we use the AWS plugin for velero with it) and would like to use the etcd-backup-operator.

**Comment by ChandranshuRao14** [comment]
Any update on this feature request? We have the exact same use case and would love to see this functionality
