### ISSUE TITLE
Error in running etcd-backup-operator. No ETCDBackup kind found

### ISSUE THREAD

**Issue by varunjain0606** [giantswarm/etcd-backup-operator#239]
I am trying to run etcd-backup-operator inside my cluster but getting the below error. 

```
{"caller":"github.com/giantswarm/backoff@v0.2.0/notifier.go:13","controller":"etcd-backup-operator-etcd-backup-controller","level":"warning","message":"retrying backoff in '1s' due to error","stack":{"annotation":"**no matches for kind \"ETCDBackup\" in version \"backup.giantswarm.io/v1alpha1\"**","kind":"unknown","stack":[{"file":"/Users/vjain/go/pkg/mod/github.com/giantswarm/operatorkit/v4@v4.3.1/pkg/controller/controller.go","line":432},{"file":"/Users/vjain/go/pkg/mod/github.com/giantswarm/operatorkit/v4@v4.3.1/pkg/controller/controller.go","line":261}]},"time":"2021-09-23T12:08:13.77609+00:00"}
{"caller":"github.com/giantswarm/exporterkit/collector/set.go:48","level":"debug","message":"booting collector","time":"2021-09-23T12:08:14.77676+00:00"}
```

Steps I followed:

1. Cloned the repository and made some changes related to s3. Basically added endpoint for the aws and creating bucket if does not exist already. Very small change
2. Ran make build-linux as dockerfile is gonna run in alpine os and I am using macOS
3. Generated docker build
4. Pushed the custom docker image
5. Used that image and tag in the helm values. 
6. Ran helm install 
7. I can see the helm deployed but in the pods getting the above error.

▶ helm install etcd-backup-operator etcd-backup-operator --namespace varun
NAME: etcd-backup-operator
LAST DEPLOYED: Thu Sep 23 17:37:34 2021
NAMESPACE: varun
STATUS: deployed
REVISION: 1
TEST SUITE: None

▶ kg cronjob -n varun                                                     
NAME                             SCHEDULE      SUSPEND   ACTIVE   LAST SCHEDULE   AGE
etcd-backup-operator-scheduler   0/3 * * * *   False     0        <none>          18s

▶ kg pods -n varun
NAME                                   READY   STATUS             RESTARTS   AGE
etcd-backup-operator-d699b7fcc-x4sr7   0/1     CrashLoopBackOff   1          29s

**Comment by fiunchinho** [comment]
Hey @varunjain0606 . The etcd-backup-operator relies on a [Custom Resource Definition](https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/) to represent how the backups will be done. The error you get is telling you that the CRD is missing from the kubernetes cluster. You need to [apply this CRD](https://github.com/giantswarm/apiextensions/blob/master/config/crd/backup.giantswarm.io_etcdbackups.yaml)
```
kubectl apply -f https://raw.githubusercontent.com/giantswarm/apiextensions/master/config/crd/backup.giantswarm.io_etcdbackups.yaml
```

**Comment by fiunchinho** [comment]
I'm closing this. If you have further questions feel free to reopen!

**Comment by varunjain0606** [comment]
Sure @fiunchinho. Thanks for the help
